baseURL = 'https://lxh21k.github.io'
languageCode = 'en-us'
title = 'Leooooooo'
theme ='paper'

[params]
  # color style
  color = 'linen'                 # linen, wheat, gray, light

  # header social icons
  twitter = 'Robot_Le0'    # twitter.com/YOUR_TWITTER_ID
  github = 'lxh21k'       # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                      # show rss icon with link

  # home page profile
  # avatar = 'GRAVATAR_EMAIL'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  # name = 'YOUR_NAME'
  # bio = 'YOUR_BIO'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = true             # show monochrome dark mode icon

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
